namespace Domain.Models.Structure
{
    public struct STHost
    {
        public string szTID;
        public string szMID;
        public string szServerCertName;
        public string szHostTemplate;
        public string szPaymentTemplate;
        public string szSecondEntryTemplate;
        public string szMesgTemplate; // Added on 27 Oct 2009
        public string szURL;
        public string szQueryURL;
        public string szReversalURL;
        public string szAcknowledgementURL;
        public string szCancelURL;
        public string szReturnURL;
        public string szReturnURL2; // Added on 22 Oct 2009
        public string szReturnIPAddresses;
        public string szDBConnStr;
        public string szOSPymtCode;
        public string szSendKey; // Secret key to form hash value for request to Host
        public string szReturnKey; // Secret key to form hash value for response from Host
        public string szHashMethod;
        public string szHashValue;
        public string szSecretKey;
        public string szInitVector;
        public string szReserved; // Reserved field to store Host reply, especially for the whole encrypted reply
        public string szReserved2; // Added by Jeff, 24 Sept 2015, for Bitnet
        public string szAcquirerID;
        public string szPayeeCode;
        public string szRunningNo; // Trace Number/Running Number - Added on 19 Sept 2010
        public string szDesc; // Host Description - Added by Jeff, 9 Dec 2013
        public string szProtocol; // Security Protocol, e.g. SSL3, TLS, TLS1.1, TLS1.2 - Added by Jeff, 21 Jun 2015
        public string szChannelCfg1; // Added by Jeff, 1 Sept 2015, Bitnet
        public string szChannelCfg2; // Added by Jeff, 1 Sept 2015, Bitnet
        public string szFixedCurrency; // Added by Jeff, 25 Sept 2015, Bitnet
        public string szLogoPath; // Added by FoongMei, 23 Oct 2015
        public string szCertId; // Added by FoongMei, 05 Feb 2016, for GPUPOP to store Cert Serial Number get from 1st time in Query String

        public int iChannelID;
        public int iHostID;
        public int iPortNumber;
        public int iQueryPortNumber;
        public int iReversalPortNumber;
        public int iAcknowledgementPortNumber;
        public int iCancelPortNumber;
        public long iTimeOut;
        public long iChannelTimeOut; // Timeout - Added by Jeff, 18 Nov 2015, MOTO, cater for receive timeout between IPG and MPG
        public long iOTCRevTimeOut; // OTC Reversal Timeout - Added by Vivek, 24 Jul 2015
        public int iRequire2ndEntry;
        public int iNeedReplyAcknowledgement;
        public int iNeedRedirectOTP; // Added on 21 Mar 2010
        public int iTxnStatusActionID;
        public int iHostReplyMethod;
        public int iGatewayTxnIDFormat;
        public int iQueryFlag; // Query flag to determine whether to query the host
        public int iIsActive; // Flag to indicate whether Host is enabled or disabled
        public int iAllowQuery; // Added by OoiMei, 9 Jun 2014. Firefly FFCTB
        public int iAllowReversal; // Flag to indicate whether Host supports Reversal Sale or Refund - Added on 10 Apr 2010
        public int iNoOfRunningNo; // Number of digits for Trace Number or Running Number - Added on 18 Sept 2010
        public int iRunningNoUniquePerDay; // Boolean to indicate whether Trace Number or Running Number is unique per day - Added on 18 Sept 2010
        public int iLogRes; // Added by OoiMei, 23 Oct 2014. Firefly FFAMBANK
        public bool bIsHashOptional; // Added by OoiMei, 27 Aug 2015. PBB.
        public int iOTCGenMethod; // Added by Vicky-711, 8 Apr 2016, to specify whether OTC Secure Code generated by eGHL(1) or Host(2)
        public string szSelectedCurrExpnt; // Added by OoiMei, 13 Sept 2017. FYAMEX
        public int iMerchantHostTimeout; // Added by Jeff, 4 Jan 2018, Atomy FPX 1-hour expiry
        public string szPymtMethod; // Added by Jeff, 19 Jun 2018, to solve pass in PymtMethod not matched IssuingBank 7Con
        public int iECIAlerts; // Added by Fauzan, 29 Aug 2018. ECI Alert Email
        public int iOnCVV; // Added by LeeLin, 12 Nov 2018, MPGS
        public int iAllowAuth; // Added by HFM, 25 Oct 2019, Alipay PreAuth
        public int iHostMPI; // Added by HFM, 17 Sep 2020, 11 Jan 2021, 3DSS
        public int iHostSupport3DS; // Added by XinYi, 11 Jan 2021, 3DSS
        public int iRefundType; // Added by Christian C., 5 Jan 2021, 25 Jan 2021, 11 Feb 2021, BBL CC, host only allow Full Refund
        public string szTerminalMID; // Added by Jeff+YS, 16 May 2023, RPP
        public int iTokenization; // Added by Kelvin+Jeff, 18 May 2023, MyDebitCNP Tokenization
        public int iHostSvcType;

        public string szClientID; // Added by LWC, 21 Dec 2021, RHBMPGS
        public string szAccessKey; // Added by LWC, 21 Dec 2021, RHBMPGS
        public string szEncryptionKey; // Added by LWC, 21 Dec 2021, RHBMPGS
        public string szSecurityKey; // Added by LWC, 21 Dec 2021, RHBMPGS
        public string szAuthenticatePayerURL; // Added by LWC, 21 Dec 2021, RHBMPGS. Used by MyDebit CNP (NKH001CNP)
        public string szInitAuthenticationURL; // Added by LL, 16 Apr 2022, MPGSNOTCALL
        public string szAPIReqURL; // Added by LWC, 14 Aug 2022, MBBMGATE, encoded URL in header signature
        public int iAuthDurationHour; // Added by Alex Ng Nkh, 19 Jan 2022, 31 Aug 2022, MyDebit CNP (NKH002CNP)
        public int iCaptureType; // Added by Alex Ng Nkh, 19 Jan 2022, 31 Aug 2022, MyDebit CNP (NKH002CNP)
        public int iReversalTimeout; // Added by XinYi, 31 Aug 2022, MyDebit CNP
        public string szWebAPIKey; // Added by Jeff+LiWen, 28 Jan 2023, TMB
        public string szHostMerchantPassword; // Added by Jeff+LiWen, 2 Feb 2023, TMB
        public int szHostTokenization; // Added by Kelvin, 7 June 2023, MyDebitTokenization (new flag to check tokenization)
        public string szHostCode; // Added by Kelvin, 7 June 2023, MyDebitTokenization (HostCode)
        public string szHostQueryTokenURL; // Added by Kelvin, 28 July 2023, To Query Token PAN from microservices

        public STHost()
        {
            szTID = "";
            szMID = "";
            szServerCertName = "";
            szHostTemplate = "";
            szPaymentTemplate = "";
            szSecondEntryTemplate = "";
            szMesgTemplate = "";
            szURL = "";
            szQueryURL = "";
            szReversalURL = "";
            szAcknowledgementURL = "";
            szCancelURL = "";
            szReturnURL = "";
            szReturnURL2 = "";
            szReturnIPAddresses = "";
            szDBConnStr = "";
            szOSPymtCode = "";
            szSendKey = "";
            szReturnKey = "";
            szHashMethod = "";
            szHashValue = "";
            szSecretKey = "";
            szInitVector = "";
            szReserved = "";
            szReserved2 = "";
            szAcquirerID = "";
            szPayeeCode = "";
            szRunningNo = "";
            szDesc = "";
            szProtocol = "";
            szChannelCfg1 = "";
            szChannelCfg2 = "";
            szFixedCurrency = "";
            szLogoPath = "";
            szCertId = "";

            iChannelID = 0;
            iHostID = 0;
            iPortNumber = 0;
            iQueryPortNumber = 0;
            iReversalPortNumber = 0;
            iAcknowledgementPortNumber = 0;
            iCancelPortNumber = 0;
            iTimeOut = 900;
            iChannelTimeOut = 900;
            iOTCRevTimeOut = 0;
            iRequire2ndEntry = 0;
            iNeedReplyAcknowledgement = 0;
            iNeedRedirectOTP = 0;
            iTxnStatusActionID = 0;
            iHostReplyMethod = 0;
            iGatewayTxnIDFormat = 0;
            iQueryFlag = 1;
            iIsActive = 1;
            iAllowQuery = 0;
            iAllowReversal = 0;
            iNoOfRunningNo = 0;
            iRunningNoUniquePerDay = 0;
            iLogRes = 1;
            bIsHashOptional = false;
            iOTCGenMethod = 0;
            szSelectedCurrExpnt = "";
            iMerchantHostTimeout = 0;
            szPymtMethod = "";
            iECIAlerts = 0;
            iOnCVV = 0;
            iAllowAuth = -1;
            iHostMPI = 0;
            iHostSupport3DS = 0;
            iRefundType = 0;
            szTerminalMID = "";
            iTokenization = 0;
            iHostSvcType = 2;
            szClientID = "";
            szAccessKey = "";
            szEncryptionKey = "";
            szSecurityKey = "";
            szAuthenticatePayerURL = "";
            szInitAuthenticationURL = "";
            szAPIReqURL = "";
            iAuthDurationHour = 0;
            iCaptureType = 0;
            iReversalTimeout = 0;
            szWebAPIKey = "";
            szHostMerchantPassword = "";
            szHostTokenization = 0;
            szHostCode = "";
            szHostQueryTokenURL = "";
        }
    }
}
